<?php
// $Id$

/**
 * @file
 * Part of the vote_up_down project
 */

/**
 * Implementation of hook_help().
 */
function user_navigation_help($section) {
  switch ($section) {
    case 'admin/modules#description':
      $output = t('Block that display links for the users account.');
      break;
  }
  return $output;
}

/**
 * Implementation of hook_block().
 */

function user_navigation_block($op = 'list', $delta = 0) {
  if ($op == 'list') {
    $blocks[0]['info'] = t('User account links');
    return $blocks;
  }
  else if ($op == 'view') {
    global $user;
    if ($user->uid) {
      $items = array();
      $items[] = l(t('my account'), 'user/'. $user->uid);
      $items[] = l(t('my posts'), 'storylink/'. $user->uid);
      $items[] = l(t('log out'), 'logout');

      $block['subject'] = $user->name;
      $block['content'] = theme('item_list', $items);
    }
    return $block;
  }
}
?>
