<?php
// $Id$

/*
 * @file
 * vote_storylink defines a "storylink" node type.
 * It's based upon "links_weblink.module".
 */

/**
 * Implementation of hook_help()
 */
function vote_storylink_help($section) {
  switch ($section) {
    case 'admin/help#vote_storylink':
      return t("<p>This module is used to create links to other resources -- websites, pages, documents, etc. Each click on an outgoing link is logged and counted.</p>");
    case 'admin/modules#description':
      return t("Creates articles whose main purpose is to catalog a story link");
    case 'node/add#storylink':
      return t("A storylink is an article whose main purpose is to catalog a link into a directory, as distinguished from an article of some other type that may or may not have related links. It is possible that a storylink article may <i>also</i> have related links (depending on administrative settings for this site), but the storylink's primary link is a required field that is separate from the optional related links (if any).");
  }
}

/**
 * Implementation of hook_node_info()
 */
function vote_storylink_node_info() {
  return array('storylink' => array('name' => t('story link'), 'base' => 'vote_storylink'));
}

/**
 * Implementation of hook_perm
 */
function vote_storylink_perm() {
  return array('create storylinks', 'edit own storylinks');
}

/**
 * Implementation of hook_access()
 */
function vote_storylink_access($op, $node) {
  global $user;

  if ($op == 'create') {
    return user_access('create storylinks');
  }

  if ($op == 'update' || $op == 'delete') {
    if (user_access('edit own storylinks') && ($user->uid == $node->uid)) {
      return TRUE;
    }
  }
}

/**
 * Implementation of hook_menu()
 */
function vote_storylink_menu($may_cache) {
  $items = array();

  if ($may_cache) {
    $items[] = array(
      'path' => 'node/add/storylink',
      'title' => t('story link'),
      'access' => user_access('create storylinks')
      );
    $items[] = array(
      'path' => 'storylink',
      'title' => t('story links'),
      'callback' => 'vote_storylink_page',
      'access' => user_access('access content'),
      'type' => MENU_CALLBACK
      );
  }

  return $items;
}

/**
 * Menu callback; displays a Drupal page containing recent story links entries.
 */
function vote_storylink_page($a = NULL, $b = NULL) {

  if (is_numeric($a)) { // $a is a user ID
    if ($b == 'feed') {
      return vote_storylink_feed_user($a);
    }
    else {
      return vote_storylink_page_user($a);
    }
  }
  elseif ($a == 'top') {
    if ($b == 'feed') {
      return vote_storylink_feed_top();
    }
    else {
      return vote_storylink_page_top();
    }
  }
  elseif ($a == 'new' && $b == 'feed') {
    return vote_storylink_feed_new();
  }
  else {
    return vote_storylink_page_new();
  }
}

/**
 * Display views of the storylinks
 */
function vote_storylink_page_new($a = NULL, $b = NULL) {
  drupal_set_title(t('new story links') . $a . $b);
  $sql = db_rewrite_sql("SELECT n.nid, n.created FROM {node} n WHERE n.type = 'storylink' AND n.status = 1 ORDER BY n.created DESC");
  $result = pager_query($sql, variable_get('default_nodes_main', 10));
  while ($node = db_fetch_object($result)) {
    $output .= node_view(node_load($node->nid), 1);
  }
  $output .= theme('pager', NULL, variable_get('default_nodes_main', 10));
  $output .= theme('feed_icon', url('storylink/new/feed'));

  drupal_add_link(array('rel' => 'alternate',
                        'type' => 'application/rss+xml',
                        'title' => t('RSS - %title', array('%title' => $title)),
                        'href' => url('storylink/new/feed')));

  return $output;
}

function vote_storylink_page_top() {
  drupal_set_title(t('popular story links'));
  $sql = db_rewrite_sql("SELECT n.nid, v.content_id, v.value, v.tag, v.function FROM {node} n INNER JOIN {votingapi_cache} v ON n.nid = v.content_id WHERE n.type = 'storylink' AND n.status = 1 AND v.tag = 'vote' AND v.function = 'sum' ORDER BY v.value DESC");
  $result = pager_query($sql, variable_get('default_nodes_main', 10));
  while ($node = db_fetch_object($result)) {
    $output .= node_view(node_load($node->nid), 1);
  }
  $output .= theme('pager', NULL, variable_get('default_nodes_main', 10));
  $output .= theme('feed_icon', url('storylink/top/feed'));

  drupal_add_link(array('rel' => 'alternate',
                        'type' => 'application/rss+xml',
                        'title' => t('RSS - %title', array('%title' => $title)),
                        'href' => url('storylink/top/feed')));

  return $output;
}

/**
 * Displays a Drupal page containing recent storylink entries of a given user.
 */
function vote_storylink_page_user($uid) {
  global $user;

  $account = user_load(array((is_numeric($uid) ? 'uid' : 'name') => $uid, 'status' => 1));

  if ($account->uid) {
    drupal_set_title($title = t("%name's storylinks", array('%name' => $account->name)));

    $result = pager_query(db_rewrite_sql("SELECT n.nid, n.created FROM {node} n WHERE type = 'storylink' AND n.uid = %d AND n.status = 1 ORDER BY n.created DESC"), variable_get('default_nodes_main', 10), 0, NULL, $account->uid);
    while ($node = db_fetch_object($result)) {
      $output .= node_view(node_load($node->nid), 1);
    }
    $output .= theme('pager', NULL, variable_get('default_nodes_main', 10));
    $output .= theme('feed_icon', url("storylink/$account->uid/feed"));

    drupal_add_link(array('rel' => 'alternate',
                          'type' => 'application/rss+xml',
                          'title' => t('RSS - %title', array('%title' => $title)),
                          'href' => url("storylink/$account->uid/feed")));
    return $output;
  }
  else {
    drupal_not_found();
  }
}

/**
 * Displays an RSS feed containing recent storylink entries of all users.
 */
function vote_storylink_feed_new() {
  $result = db_query_range(db_rewrite_sql("SELECT n.nid, n.title, n.created, r.teaser FROM {node} n INNER JOIN {node_revisions} r ON n.vid = r.vid WHERE n.type = 'storylink' AND n.status = 1 ORDER BY n.created DESC"), 0, variable_get('feed_default_items', 10));
  $channel['title'] = variable_get('site_name', 'drupal') .' new';
  $channel['link'] = url('storylink/new', NULL, NULL, TRUE);
  $channel['description'] = $term->description;
  node_feed($result, $channel);
}

function vote_storylink_feed_top() {
  $result = db_query_range(db_rewrite_sql("SELECT n.nid, n.title, r.teaser, v.content_id, v.value, v.tag, v.function FROM {node} n INNER JOIN {node_revisions} r ON n.vid = r.vid INNER JOIN {votingapi_cache} v ON n.nid = v.content_id WHERE n.type = 'storylink' AND n.status = 1 AND v.tag = 'vote' AND v.function = 'sum' ORDER BY v.value DESC"), 0, variable_get('feed_default_items', 10));
  $channel['title'] = variable_get('site_name', 'drupal') .' popular';
  $channel['link'] = url('storylink/top', NULL, NULL, TRUE);
  $channel['description'] = $term->description;
  node_feed($result, $channel);
}

function vote_storylink_feed_user($uid = 0) {
  global $user;

  if ($uid) {
    $account = user_load(array('uid' => $uid, 'status' => 1));
  }
  else {
    $account = $user;
  }

  $result = db_query_range(db_rewrite_sql("SELECT n.nid, n.title, n.created, r.teaser, u.name, u.uid FROM {node} n INNER JOIN {node_revisions} r ON n.vid = r.vid INNER JOIN {users} u ON n.uid = u.uid WHERE n.type = 'storylink' AND u.uid = %d AND n.status = 1 ORDER BY n.created DESC"), $uid, 0, variable_get('feed_default_items', 10));
  $channel['title'] = $account->name ."'s storylinks";
  $channel['link'] = url("storylink/$uid", NULL, NULL, TRUE);
  $channel['description'] = $term->description;
  node_feed($result, $channel);
}

/**
 * Implementation of hook_user().
 */
function vote_storylink_user($type, &$edit, &$user) {
  if ($type == 'view' && user_access('create storylinks', $user)) {
    $items[] = array('title' => t('Story links'),
      'value' => l(t('view recent story links'), "storylink/$user->uid", array('title' => t("Read %username's latest story links.", array('%username' => $user->name)))),
      'class' => 'storylink',
    );
    return array(t('History') => $items);
  }
}

/**
 * Implementation of hook_form
 */
function vote_storylink_form(&$node, &$param) {
  $vote_storylink = $node->vote_storylink;

  // Allow the url field to be initialized via $_GET (e.g. for use
  // with a "blog it" bookmarklet):
  if ($_GET['edit']['url']  && !$vote_storylink[0]['url']) {
    $story_url = check_url($_GET['edit']['url']);
  }
  else {
    $story_url = $vote_storylink[0]['url'];
  }

  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => t('Title'),
    '#required' => TRUE,
    '#default_value' => $node->title,
    '#maxlength' => 80,
    '#description' => t("Titel of the story the link goes to, max 80 characters."),
    '#weight' => -18,
  );

  $form['vote_storylink_url'] = array(
    '#type' => 'textfield',
    '#title' => t('URL'),
    '#value' => $story_url,
    '#required' => TRUE,
    '#description' => t('The URL/address of the story.'),
    '#weight' => -17,
  );

  $form['body'] = array(
    '#type' => 'textarea',
    '#title' => t('Description'),
    '#default_value' => $node->body,
    '#required' => FALSE,
    '#rows' => 5,
    '#maxlength' => 300,
    '#resizable' => FALSE,
    '#description' => t('A short description of the story. It should be around 2 to 4 sentences.'),
    '#weight' => -16,
  );

  return $form;
}

/**
 * Implementation of hook_load
 */
function vote_storylink_load($node) {
  $links = links_load_links_for_node($node->nid, 'vote_storylink', 0, TRUE);
  return array('vote_storylink_url' => $links[0]['url'], 'vote_storylink' => $links);
}

/**
 * Implementation of hook_prepare().
 */
function vote_storylink_prepare(&$node) {
  if (isset($_POST['edit']['vote_storylink_url'])) {
    $node->vote_storylink_url = $_POST['edit']['vote_storylink_url'];
  }
  vote_storylink_node_build($node);
}

/**
 * Implementation of hook_validate().
 */
function vote_storylink_validate(&$node) {
  vote_storylink_node_build($node);
}

/**
 * Implementation of hook_delete().
 */
function vote_storylink_delete(&$node) {
  // Delete the values from a node that is being erased
  // Don't care if it's "supposed" to have links -- delete if found anyway
  vote_storylink_node_build($node);
  links_delete_links_for_node($node, 'vote_storylink');
}

/**
 * Implementation of hook_insert().
 */
function vote_storylink_insert(&$node) {
  vote_storylink_node_build($node);
  links_save_links_for_node($node, 'vote_storylink');
}

/**
 * Implementation of hook_update().
 */
function vote_storylink_update(&$node) {
  vote_storylink_node_build($node);
  links_save_links_for_node($node, 'vote_storylink');
}

/**
 * Implementation of hook_link().
 */
function vote_storylink_link($type, $node = NULL, $teaser = FALSE) {
  $links = array();

  if ($type == 'node' && $node->type == 'storylink') {
    $links[] = l(t('more'), 'node/'. $node->nid);
    //return links_get_list('vote_storylink', $node, FALSE, $teaser);
  }

  return $links;
}

/**
 * Implementation of hook_view
 */
function vote_storylink_view(&$node, $teaser = FALSE, $page = FALSE) { 
  if ($teaser || ! intval(variable_get('vote_storylink_enable_list', 0))) {
    // No changes in teaser mode or if appended link disabled
    return;
  }
  $formatted_links = links_get_list('vote_storylink', $node, $page, $teaser);
  // We know the array can only have zero or one elements in this module.
  if (isset($formatted_links[0])) {
    $append = theme('vote_storylink_append', $formatted_links[0]);
  }
  $node->body .= $append;
  $node = node_prepare($node, $teaser); 
}

/**
 * Apply markup to the appended storylink
 */
function theme_vote_storylink_append($link_markup) {
  $output = '<p><ul id="vote_storylink_list"><li>' . $link_markup . '</li></ul>';
  return $output;
}

function theme_vote_storylink_via($link_url) {
  $link_url = parse_url($link_url);
  $output = '<div class="vote-up-down-via">('. t('via %domain ', array('%domain' => $link_url['host'])) . ')</div>';
  return $output;
}

/**
 * To use the links API, we sometimes need to populate the internal data
 * structure $node->vote_storylink, which is an array of link-definition
 * arrays. In this case, the outer array always contains exactly one element
 * because we are interested only in the primary URL for the storylink. If
 * this site allows "related links" for storylink nodes, that's handled
 * by the links_related module, not here.
 */
function vote_storylink_node_build(&$node, $url='') {
  if (empty($url)) {
    $url = links_normalize_url($node->vote_storylink_url);
  } else {
    $url = links_normalize_url($url);
  }
  $node->vote_storylink_url = $url;
  $link = array(
    'url' => $url,
    'link_title' => $node->title,
    'weight' => 0,
  );
  // Wrap $link as the [0] element of a trivial outer array.
  $node->vote_storylink = array($link);
}

/**
 * Create the form for the node. It's similar to the form for links_related
 * but allows (and in fact requires) only one link. Note that it's possible
 * to enable the "storylink" node type for "related links" in addition to the
 * special link that is a requirement. The only difference is the $module
 * parameter when we save the link to the database.
 */
function vote_storylink_form_alter($form_id, &$form) {
  $type = $form['type']['#value'];
  switch ($form_id) {
    case $type .'_node_form':
      // The actual node edit form. This allows the users to enter the
      // links_related into appropriate node types' edit screens.
      $node = $form['#node'];
      $link = $node->vote_storylink;
      $link['url'] = links_normalize_url($link['url']);
    break;
  }
  return;
}

?>
